export const CountryListData = [
  { CountryName: "China", CountryImpact: "7.38" },
  { CountryName: "United States", CountryImpact: "15.52" },
  { CountryName: "India", CountryImpact: "1.91" },
  { CountryName: "Russia", CountryImpact: "11.44" },
  { CountryName: "Japan", CountryImpact: "9.7" },
  { CountryName: "Germany", CountryImpact: "9.44" },
  { CountryName: "Canada", CountryImpact: "18.58" },
  { CountryName: "Iran", CountryImpact: "8.08" },
  { CountryName: "South Korea", CountryImpact: "11.85" },
  { CountryName: "Indonesia", CountryImpact: "2.03" },
  { CountryName: "Saudi Arabia", CountryImpact: "15.94" },
  { CountryName: "Brazil", CountryImpact: "2.25" },
  { CountryName: "Mexico", CountryImpact: "3.58" },
  { CountryName: "Australia", CountryImpact: "17.1" },
  { CountryName: "South Africa", CountryImpact: "6.95" },
  { CountryName: "Turkey", CountryImpact: "4.61" },
  { CountryName: "United Kingdom", CountryImpact: "5.55" },
  { CountryName: "Italy", CountryImpact: "5.9" },
  { CountryName: "France", CountryImpact: "5.13" },
  { CountryName: "Poland", CountryImpact: "7.81" },
  { CountryName: "Taiwan", CountryImpact: "11.72" },
  { CountryName: "Thailand", CountryImpact: "3.93" },
  { CountryName: "Malaysia", CountryImpact: "8.68" },
  { CountryName: "Spain", CountryImpact: "5.4" },
  { CountryName: "Ukraine", CountryImpact: "5.22" },
  { CountryName: "Kazakhstan", CountryImpact: "13.01" },
  { CountryName: "Egypt", CountryImpact: "2.32" },
  { CountryName: "United Arab Emirates", CountryImpact: "23.37" },
  { CountryName: "Vietnam", CountryImpact: "2.2" },
  { CountryName: "Argentina", CountryImpact: "4.61" },
  { CountryName: "Pakistan", CountryImpact: "0.87" },
  { CountryName: "Netherlands", CountryImpact: "9.62" },
  { CountryName: "Iraq", CountryImpact: "4.44" },
  { CountryName: "Algeria", CountryImpact: "3.85" },
  { CountryName: "Philippines", CountryImpact: "1.22" },
  { CountryName: "Czech Republic (Czechia)", CountryImpact: "10.53" },
  { CountryName: "Uzbekistan", CountryImpact: "3.48" },
  { CountryName: "Kuwait", CountryImpact: "25.65" },
  { CountryName: "Qatar", CountryImpact: "37.29" },
  { CountryName: "Belgium", CountryImpact: "8.34" },
  { CountryName: "Oman", CountryImpact: "19.61" },
  { CountryName: "Nigeria", CountryImpact: "0.44" },
  { CountryName: "Chile", CountryImpact: "4.46" },
  { CountryName: "Turkmenistan", CountryImpact: "14" },
  { CountryName: "Romania", CountryImpact: "3.98" },
  { CountryName: "Colombia", CountryImpact: "1.61" },
  { CountryName: "Bangladesh", CountryImpact: "0.47" },
  { CountryName: "Austria", CountryImpact: "8.43" },
  { CountryName: "Greece", CountryImpact: "6.39" },
  { CountryName: "Israel", CountryImpact: "8.04" },
  { CountryName: "Belarus", CountryImpact: "6.63" },
  { CountryName: "North Korea", CountryImpact: "2.32" },
  { CountryName: "Morocco", CountryImpact: "1.64" },
  { CountryName: "Peru", CountryImpact: "1.87" },
  { CountryName: "Libya", CountryImpact: "8.12" },
  { CountryName: "Finland", CountryImpact: "9.31" },
  { CountryName: "Hungary", CountryImpact: "5.23" },
  { CountryName: "Bulgaria", CountryImpact: "7.11" },
  { CountryName: "Portugal", CountryImpact: "4.86" },
  { CountryName: "Singapore", CountryImpact: "8.56" },
  { CountryName: "Hong Kong", CountryImpact: "6.5" },
  { CountryName: "Sweden", CountryImpact: "4.54" },
  { CountryName: "Norway", CountryImpact: "8.28" },
  { CountryName: "Serbia", CountryImpact: "4.65" },
  { CountryName: "Ecuador", CountryImpact: "2.43" },
  { CountryName: "Switzerland", CountryImpact: "4.73" },
  { CountryName: "Ireland", CountryImpact: "8.32" },
  { CountryName: "Syria", CountryImpact: "2.18" },
  { CountryName: "Denmark", CountryImpact: "6.65" },
  { CountryName: "Slovakia", CountryImpact: "6.77" },
  { CountryName: "Trinidad and Tobago", CountryImpact: "25.39" },
  { CountryName: "Azerbaijan", CountryImpact: "3.45" },
  { CountryName: "New Zealand", CountryImpact: "7.14" },
  { CountryName: "Angola", CountryImpact: "1.06" },
  { CountryName: "Cuba", CountryImpact: "2.68" },
  { CountryName: "Tunisia", CountryImpact: "2.6" },
  { CountryName: "Bosnia and Herzegovina", CountryImpact: "7.58" },
  { CountryName: "Yemen", CountryImpact: "0.94" },
  { CountryName: "Bahrain", CountryImpact: "17.15" },
  { CountryName: "Dominican Republic", CountryImpact: "2.26" },
  { CountryName: "Jordan", CountryImpact: "2.38" },
  { CountryName: "Estonia", CountryImpact: "17.02" },
  { CountryName: "Lebanon", CountryImpact: "3.26" },
  { CountryName: "Bolivia", CountryImpact: "1.76" },
  { CountryName: "Croatia", CountryImpact: "4.61" },
  { CountryName: "Mongolia", CountryImpact: "6.08" },
  { CountryName: "Guatemala", CountryImpact: "1.12" },
  { CountryName: "Sri Lanka", CountryImpact: "0.88" },
  { CountryName: "Myanmar", CountryImpact: "0.31" },
  { CountryName: "Kenya", CountryImpact: "0.33" },
  { CountryName: "Montenegro", CountryImpact: "25.9" },
  { CountryName: "Slovenia", CountryImpact: "7.1" },
  { CountryName: "Ghana", CountryImpact: "0.51" },
  { CountryName: "Lithuania", CountryImpact: "4.74" },
  { CountryName: "Sudan", CountryImpact: "0.33" },
  { CountryName: "Panama", CountryImpact: "2.87" },
  { CountryName: "Ethiopia", CountryImpact: "0.1" },
  { CountryName: "Luxembourg", CountryImpact: "17.51" },
  { CountryName: "Zimbabwe", CountryImpact: "0.72" },
  { CountryName: "Côte d'Ivoire", CountryImpact: "0.42" },
  { CountryName: "Afghanistan", CountryImpact: "0.28" },
  { CountryName: "Tanzania", CountryImpact: "0.18" },
  { CountryName: "Cameroon", CountryImpact: "0.4" },
  { CountryName: "Honduras", CountryImpact: "1.01" },
  { CountryName: "Papua New Guinea", CountryImpact: "1.1" },
  { CountryName: "Jamaica", CountryImpact: "3.08" },
  { CountryName: "North Macedonia", CountryImpact: "4.28" },
  { CountryName: "Georgia", CountryImpact: "2.14" },
  { CountryName: "Costa Rica", CountryImpact: "1.7" },
  { CountryName: "Moldova", CountryImpact: "2.03" },
  { CountryName: "Senegal", CountryImpact: "0.55" },
  { CountryName: "Latvia", CountryImpact: "4.13" },
  { CountryName: "Nepal", CountryImpact: "0.29" },
  { CountryName: "Brunei", CountryImpact: "18.28" },
  { CountryName: "Kyrgyzstan", CountryImpact: "1.14" },
  { CountryName: "Cyprus", CountryImpact: "5.87" },
  { CountryName: "El Salvador", CountryImpact: "1.08" },
  { CountryName: "DR Congo", CountryImpact: "0.08" },
  { CountryName: "Benin", CountryImpact: "0.6" },
  { CountryName: "Uruguay", CountryImpact: "1.9" },
  { CountryName: "Cambodia", CountryImpact: "0.41" },
  { CountryName: "Botswana", CountryImpact: "2.98" },
  { CountryName: "Tajikistan", CountryImpact: "0.7" },
  { CountryName: "Paraguay", CountryImpact: "0.89" },
  { CountryName: "Mozambique", CountryImpact: "0.21" },
  { CountryName: "Gabon", CountryImpact: "2.84" },
  { CountryName: "Nicaragua", CountryImpact: "0.84" },
  { CountryName: "Congo", CountryImpact: "1.05" },
  { CountryName: "Albania", CountryImpact: "1.8" },
  { CountryName: "Uganda", CountryImpact: "0.13" },
  { CountryName: "Armenia", CountryImpact: "1.57" },
  { CountryName: "Laos", CountryImpact: "0.66" },
  { CountryName: "Bahamas", CountryImpact: "11.65" },
  { CountryName: "Zambia", CountryImpact: "0.26" },
  { CountryName: "South Sudan", CountryImpact: "0.37" },
  { CountryName: "Iceland", CountryImpact: "11.81" },
  { CountryName: "Namibia", CountryImpact: "1.65" },
  { CountryName: "Guyana", CountryImpact: "4.22" },
  { CountryName: "Mauritius", CountryImpact: "2.53" },
  { CountryName: "Macao", CountryImpact: "5.07" },
  { CountryName: "Haiti", CountryImpact: "0.28" },
  { CountryName: "Madagascar", CountryImpact: "0.12" },
  { CountryName: "Martinique", CountryImpact: "7.21" },
  { CountryName: "Mauritania", CountryImpact: "0.62" },
  { CountryName: "Guadeloupe", CountryImpact: "6.2" },
  { CountryName: "Burkina Faso", CountryImpact: "0.13" },
  { CountryName: "New Caledonia", CountryImpact: "8.53" },
  { CountryName: "Togo", CountryImpact: "0.31" },
  { CountryName: "Malta", CountryImpact: "5.18" },
  { CountryName: "Equatorial Guinea", CountryImpact: "1.77" },
  { CountryName: "Suriname", CountryImpact: "3.81" },
  { CountryName: "Niger", CountryImpact: "0.1" },
  { CountryName: "Guinea", CountryImpact: "0.18" },
  { CountryName: "Malawi", CountryImpact: "0.11" },
  { CountryName: "Fiji", CountryImpact: "1.95" },
  { CountryName: "Bhutan", CountryImpact: "2.28" },
  { CountryName: "Chad", CountryImpact: "0.11" },
  { CountryName: "Mali", CountryImpact: "0.09" },
  { CountryName: "Barbados", CountryImpact: "5.39" },
  { CountryName: "Djibouti", CountryImpact: "1.62" },
  { CountryName: "French Guiana", CountryImpact: "5.5" },
  { CountryName: "Rwanda", CountryImpact: "0.12" },
  { CountryName: "Sierra Leone", CountryImpact: "0.17" },
  { CountryName: "Somalia", CountryImpact: "0.09" },
  { CountryName: "Maldives", CountryImpact: "2.59" },
  { CountryName: "Réunion", CountryImpact: "1.3" },
  { CountryName: "Belize", CountryImpact: "3.02" },
  { CountryName: "Burundi", CountryImpact: "0.1" },
  { CountryName: "French Polynesia", CountryImpact: "3.65" },
  { CountryName: "Liberia", CountryImpact: "0.18" },
  { CountryName: "Puerto Rico", CountryImpact: "0.22" },
  { CountryName: "Eritrea", CountryImpact: "0.2" },
  { CountryName: "Eswatini", CountryImpact: "0.59" },
  { CountryName: "Bermuda", CountryImpact: "10.09" },
  { CountryName: "Saint Lucia", CountryImpact: "3.38" },
  { CountryName: "Gibraltar", CountryImpact: "16.98" },
  { CountryName: "Grenada", CountryImpact: "5.03" },
  { CountryName: "Central African Republic", CountryImpact: "0.12" },
  { CountryName: "Seychelles", CountryImpact: "5.43" },
  { CountryName: "Timor-Leste", CountryImpact: "0.41" },
  { CountryName: "Antigua and Barbuda", CountryImpact: "4.64" },
  { CountryName: "Cayman Islands", CountryImpact: "6.49" },
  { CountryName: "St. Vincent & Grenadines", CountryImpact: "3.31" },
  { CountryName: "Solomon Islands", CountryImpact: "0.55" },
  { CountryName: "Guinea-Bissau", CountryImpact: "0.18" },
  { CountryName: "Lesotho", CountryImpact: "0.15" },
  { CountryName: "Aruba", CountryImpact: "2.74" },
  { CountryName: "Gambia", CountryImpact: "0.12" },
  { CountryName: "Tonga", CountryImpact: "2.49" },
  { CountryName: "Western Sahara", CountryImpact: "0.39" },
  { CountryName: "Saint Kitts & Nevis", CountryImpact: "3.93" },
  { CountryName: "Dominica", CountryImpact: "2.61" },
  { CountryName: "Samoa", CountryImpact: "0.87" },
  { CountryName: "Vanuatu", CountryImpact: "0.49" },
  { CountryName: "Comoros", CountryImpact: "0.14" },
  { CountryName: "British Virgin Islands", CountryImpact: "3.4" },
  { CountryName: "Cabo Verde", CountryImpact: "0.19" },
  { CountryName: "Turks and Caicos", CountryImpact: "1.79" },
  { CountryName: "Sao Tome & Principe", CountryImpact: "0.28" },
  { CountryName: "Kiribati", CountryImpact: "0.47" },
  { CountryName: "Falkland Islands", CountryImpact: "16.59" },
  { CountryName: "Palau", CountryImpact: "2.35" },
  { CountryName: "Cook Islands", CountryImpact: "2.13" },
  { CountryName: "Anguilla", CountryImpact: "2.1" },
  { CountryName: "Saint Helena", CountryImpact: "2.2" },
  { CountryName: "Saint Pierre & Miquelon", CountryImpact: "1.49" },
  { CountryName: "Faeroe Islands", CountryImpact: "0.04" },
  { CountryName: "Greenland", CountryImpact: "0.03" },
];
